# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sorted L1 Norm Prox
#'
#' @param x coefficients
#' @param x regularization
#'
#' @return Prox
#'
#' @export
sorted_l1_prox <- function(x, lambda) {
    .Call(`_cdslope_sorted_l1_prox`, x, lambda)
}

